apiVersion: v1
kind: Service
metadata:
  name: angularjs-db
spec:
  type: NodePort
  selector:
    app: angularjs-db
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularjs-db
  labels:
    app: angularjs-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angularjs-db
  template:
    metadata:
      labels:
        app: angularjs-db
    spec:
      containers:
        - name: angularjs-db
          image: khalil15832/angularjs-db:latest
          ports:
            - containerPort: 4200
